# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        sauth.user_manager:
            id: sauth.user_manager

    firewalls:
        main:
            pattern: ^/
            anonymous: true
            stateless: false
            simple_preauth:
                authenticator: sauth.authenticator
            provider: sauth.user_manager
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/verify, roles: ROLE_USER }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }